from otree.api import (
    models, widgets, BaseConstants, BaseSubsession, BaseGroup, BasePlayer,
    Currency as c, currency_range
)


author = 'Your name here'

doc = """
Your app description
"""


class Constants(BaseConstants):
    name_in_url = 'covering'
    players_per_group = None
    num_rounds = 1


class Subsession(BaseSubsession):
    pass


class Group(BaseGroup):
    pass


class Player(BasePlayer):

    attractive_1 = models.CharField()
    attractive_2 = models.CharField()
    attractive_3 = models.CharField()
    attractive_4 = models.CharField()
    attractive_5 = models.CharField()
    attractive_6 = models.CharField()
    attractive_7 = models.CharField()
    attractive_8 = models.CharField()
    attractive_9 = models.CharField()
    attractive_10 = models.CharField()
    attractive_11 = models.CharField()
    attractive_12 = models.CharField()
    attractive_13 = models.CharField()
    attractive_14 = models.CharField()
    attractive_15 = models.CharField()
    attractive_16 = models.CharField()
    attractive_17 = models.CharField()
    attractive_18 = models.CharField()
    attractive_19 = models.CharField()
    attractive_20 = models.CharField()
    attractive_21 = models.CharField()
    attractive_22 = models.CharField()
    attractive_23 = models.CharField()
    attractive_24 = models.CharField()
    attractive_25 = models.CharField()
    attractive_26 = models.CharField()
    attractive_27 = models.CharField()
    attractive_28 = models.CharField()
    attractive_29 = models.CharField()
    attractive_30 = models.CharField()
    attractive_31 = models.CharField()
    attractive_32 = models.CharField()
    attractive_33 = models.CharField()
    attractive_34 = models.CharField()
    attractive_35 = models.CharField()
    attractive_36 = models.CharField()
    attractive_37 = models.CharField()
    attractive_38 = models.CharField()
    attractive_39 = models.CharField()
    attractive_40 = models.CharField()
    attractive_41 = models.CharField()
    attractive_42 = models.CharField()
    attractive_43 = models.CharField()
    attractive_44 = models.CharField()
    attractive_45 = models.CharField()
    attractive_46 = models.CharField()
    attractive_47 = models.CharField()
    attractive_48 = models.CharField()
    attractive_49 = models.CharField()
    attractive_50 = models.CharField()
    attractive_51 = models.CharField()
    attractive_52 = models.CharField()
    attractive_53 = models.CharField()
    attractive_54 = models.CharField()
    attractive_55 = models.CharField()
    attractive_56 = models.CharField()
    attractive_57 = models.CharField()
    attractive_58 = models.CharField()
    attractive_59 = models.CharField()
    attractive_60 = models.CharField()
    attractive_61 = models.CharField()
    attractive_62 = models.CharField()
    attractive_63 = models.CharField()
    attractive_64 = models.CharField()
    attractive_65 = models.CharField()
    attractive_66 = models.CharField()

    masculine_1 = models.CharField()
    masculine_2 = models.CharField()
    masculine_3 = models.CharField()
    masculine_4 = models.CharField()
    masculine_5 = models.CharField()
    masculine_6 = models.CharField()
    masculine_7 = models.CharField()
    masculine_8 = models.CharField()
    masculine_9 = models.CharField()
    masculine_10 = models.CharField()
    masculine_11 = models.CharField()
    masculine_12 = models.CharField()
    masculine_13 = models.CharField()
    masculine_14 = models.CharField()
    masculine_15 = models.CharField()
    masculine_16 = models.CharField()
    masculine_17 = models.CharField()
    masculine_18 = models.CharField()
    masculine_19 = models.CharField()
    masculine_20 = models.CharField()
    masculine_21 = models.CharField()
    masculine_22 = models.CharField()
    masculine_23 = models.CharField()
    masculine_24 = models.CharField()
    masculine_25 = models.CharField()
    masculine_26 = models.CharField()
    masculine_27 = models.CharField()
    masculine_28 = models.CharField()
    masculine_29 = models.CharField()
    masculine_30 = models.CharField()
    masculine_31 = models.CharField()
    masculine_32 = models.CharField()
    masculine_33 = models.CharField()
    masculine_34 = models.CharField()
    masculine_35 = models.CharField()
    masculine_36 = models.CharField()
    masculine_37 = models.CharField()
    masculine_38 = models.CharField()
    masculine_39 = models.CharField()
    masculine_40 = models.CharField()
    masculine_41 = models.CharField()
    masculine_42 = models.CharField()
    masculine_43 = models.CharField()
    masculine_44 = models.CharField()
    masculine_45 = models.CharField()
    masculine_46 = models.CharField()
    masculine_47 = models.CharField()
    masculine_48 = models.CharField()
    masculine_49 = models.CharField()
    masculine_50 = models.CharField()
    masculine_51 = models.CharField()
    masculine_52 = models.CharField()
    masculine_53 = models.CharField()
    masculine_54 = models.CharField()
    masculine_55 = models.CharField()
    masculine_56 = models.CharField()
    masculine_57 = models.CharField()
    masculine_58 = models.CharField()
    masculine_59 = models.CharField()
    masculine_60 = models.CharField()
    masculine_61 = models.CharField()
    masculine_62 = models.CharField()
    masculine_63 = models.CharField()
    masculine_64 = models.CharField()
    masculine_65 = models.CharField()
    masculine_66 = models.CharField()

    intelligent_1 = models.CharField()
    intelligent_2 = models.CharField()
    intelligent_3 = models.CharField()
    intelligent_4 = models.CharField()
    intelligent_5 = models.CharField()
    intelligent_6 = models.CharField()
    intelligent_7 = models.CharField()
    intelligent_8 = models.CharField()
    intelligent_9 = models.CharField()
    intelligent_10 = models.CharField()
    intelligent_11 = models.CharField()
    intelligent_12 = models.CharField()
    intelligent_13 = models.CharField()
    intelligent_14 = models.CharField()
    intelligent_15 = models.CharField()
    intelligent_16 = models.CharField()
    intelligent_17 = models.CharField()
    intelligent_18 = models.CharField()
    intelligent_19 = models.CharField()
    intelligent_20 = models.CharField()
    intelligent_21 = models.CharField()
    intelligent_22 = models.CharField()
    intelligent_23 = models.CharField()
    intelligent_24 = models.CharField()
    intelligent_25 = models.CharField()
    intelligent_26 = models.CharField()
    intelligent_27 = models.CharField()
    intelligent_28 = models.CharField()
    intelligent_29 = models.CharField()
    intelligent_30 = models.CharField()
    intelligent_31 = models.CharField()
    intelligent_32 = models.CharField()
    intelligent_33 = models.CharField()
    intelligent_34 = models.CharField()
    intelligent_35 = models.CharField()
    intelligent_36 = models.CharField()
    intelligent_37 = models.CharField()
    intelligent_38 = models.CharField()
    intelligent_39 = models.CharField()
    intelligent_40 = models.CharField()
    intelligent_41 = models.CharField()
    intelligent_42 = models.CharField()
    intelligent_43 = models.CharField()
    intelligent_44 = models.CharField()
    intelligent_45 = models.CharField()
    intelligent_46 = models.CharField()
    intelligent_47 = models.CharField()
    intelligent_48 = models.CharField()
    intelligent_49 = models.CharField()
    intelligent_50 = models.CharField()
    intelligent_51 = models.CharField()
    intelligent_52 = models.CharField()
    intelligent_53 = models.CharField()
    intelligent_54 = models.CharField()
    intelligent_55 = models.CharField()
    intelligent_56 = models.CharField()
    intelligent_57 = models.CharField()
    intelligent_58 = models.CharField()
    intelligent_59 = models.CharField()
    intelligent_60 = models.CharField()
    intelligent_61 = models.CharField()
    intelligent_62 = models.CharField()
    intelligent_63 = models.CharField()
    intelligent_64 = models.CharField()
    intelligent_65 = models.CharField()
    intelligent_66 = models.CharField()

    unaggressive_1 = models.CharField()
    unaggressive_2 = models.CharField()
    unaggressive_3 = models.CharField()
    unaggressive_4 = models.CharField()
    unaggressive_5 = models.CharField()
    unaggressive_6 = models.CharField()
    unaggressive_7 = models.CharField()
    unaggressive_8 = models.CharField()
    unaggressive_9 = models.CharField()
    unaggressive_10 = models.CharField()
    unaggressive_11 = models.CharField()
    unaggressive_12 = models.CharField()
    unaggressive_13 = models.CharField()
    unaggressive_14 = models.CharField()
    unaggressive_15 = models.CharField()
    unaggressive_16 = models.CharField()
    unaggressive_17 = models.CharField()
    unaggressive_18 = models.CharField()
    unaggressive_19 = models.CharField()
    unaggressive_20 = models.CharField()
    unaggressive_21 = models.CharField()
    unaggressive_22 = models.CharField()
    unaggressive_23 = models.CharField()
    unaggressive_24 = models.CharField()
    unaggressive_25 = models.CharField()
    unaggressive_26 = models.CharField()
    unaggressive_27 = models.CharField()
    unaggressive_28 = models.CharField()
    unaggressive_29 = models.CharField()
    unaggressive_30 = models.CharField()
    unaggressive_31 = models.CharField()
    unaggressive_32 = models.CharField()
    unaggressive_33 = models.CharField()
    unaggressive_34 = models.CharField()
    unaggressive_35 = models.CharField()
    unaggressive_36 = models.CharField()
    unaggressive_37 = models.CharField()
    unaggressive_38 = models.CharField()
    unaggressive_39 = models.CharField()
    unaggressive_40 = models.CharField()
    unaggressive_41 = models.CharField()
    unaggressive_42 = models.CharField()
    unaggressive_43 = models.CharField()
    unaggressive_44 = models.CharField()
    unaggressive_45 = models.CharField()
    unaggressive_46 = models.CharField()
    unaggressive_47 = models.CharField()
    unaggressive_48 = models.CharField()
    unaggressive_49 = models.CharField()
    unaggressive_50 = models.CharField()
    unaggressive_51 = models.CharField()
    unaggressive_52 = models.CharField()
    unaggressive_53 = models.CharField()
    unaggressive_54 = models.CharField()
    unaggressive_55 = models.CharField()
    unaggressive_56 = models.CharField()
    unaggressive_57 = models.CharField()
    unaggressive_58 = models.CharField()
    unaggressive_59 = models.CharField()
    unaggressive_60 = models.CharField()
    unaggressive_61 = models.CharField()
    unaggressive_62 = models.CharField()
    unaggressive_63 = models.CharField()
    unaggressive_64 = models.CharField()
    unaggressive_65 = models.CharField()
    unaggressive_66 = models.CharField()

    trustworthy_1 = models.CharField()
    trustworthy_2 = models.CharField()
    trustworthy_3 = models.CharField()
    trustworthy_4 = models.CharField()
    trustworthy_5 = models.CharField()
    trustworthy_6 = models.CharField()
    trustworthy_7 = models.CharField()
    trustworthy_8 = models.CharField()
    trustworthy_9 = models.CharField()
    trustworthy_10 = models.CharField()
    trustworthy_11 = models.CharField()
    trustworthy_12 = models.CharField()
    trustworthy_13 = models.CharField()
    trustworthy_14 = models.CharField()
    trustworthy_15 = models.CharField()
    trustworthy_16 = models.CharField()
    trustworthy_17 = models.CharField()
    trustworthy_18 = models.CharField()
    trustworthy_19 = models.CharField()
    trustworthy_20 = models.CharField()
    trustworthy_21 = models.CharField()
    trustworthy_22 = models.CharField()
    trustworthy_23 = models.CharField()
    trustworthy_24 = models.CharField()
    trustworthy_25 = models.CharField()
    trustworthy_26 = models.CharField()
    trustworthy_27 = models.CharField()
    trustworthy_28 = models.CharField()
    trustworthy_29 = models.CharField()
    trustworthy_30 = models.CharField()
    trustworthy_31 = models.CharField()
    trustworthy_32 = models.CharField()
    trustworthy_33 = models.CharField()
    trustworthy_34 = models.CharField()
    trustworthy_35 = models.CharField()
    trustworthy_36 = models.CharField()
    trustworthy_37 = models.CharField()
    trustworthy_38 = models.CharField()
    trustworthy_39 = models.CharField()
    trustworthy_40 = models.CharField()
    trustworthy_41 = models.CharField()
    trustworthy_42 = models.CharField()
    trustworthy_43 = models.CharField()
    trustworthy_44 = models.CharField()
    trustworthy_45 = models.CharField()
    trustworthy_46 = models.CharField()
    trustworthy_47 = models.CharField()
    trustworthy_48 = models.CharField()
    trustworthy_49 = models.CharField()
    trustworthy_50 = models.CharField()
    trustworthy_51 = models.CharField()
    trustworthy_52 = models.CharField()
    trustworthy_53 = models.CharField()
    trustworthy_54 = models.CharField()
    trustworthy_55 = models.CharField()
    trustworthy_56 = models.CharField()
    trustworthy_57 = models.CharField()
    trustworthy_58 = models.CharField()
    trustworthy_59 = models.CharField()
    trustworthy_60 = models.CharField()
    trustworthy_61 = models.CharField()
    trustworthy_62 = models.CharField()
    trustworthy_63 = models.CharField()
    trustworthy_64 = models.CharField()
    trustworthy_65 = models.CharField()
    trustworthy_66 = models.CharField()

    confident_1 = models.CharField()
    confident_2 = models.CharField()
    confident_3 = models.CharField()
    confident_4 = models.CharField()
    confident_5 = models.CharField()
    confident_6 = models.CharField()
    confident_7 = models.CharField()
    confident_8 = models.CharField()
    confident_9 = models.CharField()
    confident_10 = models.CharField()
    confident_11 = models.CharField()
    confident_12 = models.CharField()
    confident_13 = models.CharField()
    confident_14 = models.CharField()
    confident_15 = models.CharField()
    confident_16 = models.CharField()
    confident_17 = models.CharField()
    confident_18 = models.CharField()
    confident_19 = models.CharField()
    confident_20 = models.CharField()
    confident_21 = models.CharField()
    confident_22 = models.CharField()
    confident_23 = models.CharField()
    confident_24 = models.CharField()
    confident_25 = models.CharField()
    confident_26 = models.CharField()
    confident_27 = models.CharField()
    confident_28 = models.CharField()
    confident_29 = models.CharField()
    confident_30 = models.CharField()
    confident_31 = models.CharField()
    confident_32 = models.CharField()
    confident_33 = models.CharField()
    confident_34 = models.CharField()
    confident_35 = models.CharField()
    confident_36 = models.CharField()
    confident_37 = models.CharField()
    confident_38 = models.CharField()
    confident_39 = models.CharField()
    confident_40 = models.CharField()
    confident_41 = models.CharField()
    confident_42 = models.CharField()
    confident_43 = models.CharField()
    confident_44 = models.CharField()
    confident_45 = models.CharField()
    confident_46 = models.CharField()
    confident_47 = models.CharField()
    confident_48 = models.CharField()
    confident_49 = models.CharField()
    confident_50 = models.CharField()
    confident_51 = models.CharField()
    confident_52 = models.CharField()
    confident_53 = models.CharField()
    confident_54 = models.CharField()
    confident_55 = models.CharField()
    confident_56 = models.CharField()
    confident_57 = models.CharField()
    confident_58 = models.CharField()
    confident_59 = models.CharField()
    confident_60 = models.CharField()
    confident_61 = models.CharField()
    confident_62 = models.CharField()
    confident_63 = models.CharField()
    confident_64 = models.CharField()
    confident_65 = models.CharField()
    confident_66 = models.CharField()

    loss_1 = models.CharField()
    loss_2 = models.CharField()
    loss_3 = models.CharField()
    loss_4 = models.CharField()
    loss_5 = models.CharField()
    loss_6 = models.CharField()
    loss_7 = models.CharField()
    loss_8 = models.CharField()
    loss_9 = models.CharField()
    loss_10 = models.CharField()
    loss_11 = models.CharField()
    loss_12 = models.CharField()
    loss_13 = models.CharField()
    loss_14 = models.CharField()
    loss_15 = models.CharField()
    loss_16 = models.CharField()
    loss_17 = models.CharField()
    loss_18 = models.CharField()
    loss_19 = models.CharField()
    loss_20 = models.CharField()
    loss_21 = models.CharField()
    loss_22 = models.CharField()
    loss_23 = models.CharField()
    loss_24 = models.CharField()
    loss_25 = models.CharField()
    loss_26 = models.CharField()
    loss_27 = models.CharField()
    loss_28 = models.CharField()
    loss_29 = models.CharField()
    loss_30 = models.CharField()
    loss_31 = models.CharField()
    loss_32 = models.CharField()
    loss_33 = models.CharField()
    loss_34 = models.CharField()
    loss_35 = models.CharField()
    loss_36 = models.CharField()
    loss_37 = models.CharField()
    loss_38 = models.CharField()
    loss_39 = models.CharField()
    loss_40 = models.CharField()
    loss_41 = models.CharField()
    loss_42 = models.CharField()
    loss_43 = models.CharField()
    loss_44 = models.CharField()
    loss_45 = models.CharField()
    loss_46 = models.CharField()
    loss_47 = models.CharField()
    loss_48 = models.CharField()
    loss_49 = models.CharField()
    loss_50 = models.CharField()
    loss_51 = models.CharField()
    loss_52 = models.CharField()
    loss_53 = models.CharField()
    loss_54 = models.CharField()
    loss_55 = models.CharField()
    loss_56 = models.CharField()
    loss_57 = models.CharField()
    loss_58 = models.CharField()
    loss_59 = models.CharField()
    loss_60 = models.CharField()
    loss_61 = models.CharField()
    loss_62 = models.CharField()
    loss_63 = models.CharField()
    loss_64 = models.CharField()
    loss_65 = models.CharField()
    loss_66 = models.CharField()

    quality_1 = models.CharField()
    quality_2 = models.CharField()
    quality_3 = models.CharField()
    quality_4 = models.CharField()
    quality_5 = models.CharField()
    quality_6 = models.CharField()
    quality_7 = models.CharField()
    quality_8 = models.CharField()
    quality_9 = models.CharField()
    quality_10 = models.CharField()
    quality_11 = models.CharField()
    quality_12 = models.CharField()
    quality_13 = models.CharField()
    quality_14 = models.CharField()
    quality_15 = models.CharField()
    quality_16 = models.CharField()
    quality_17 = models.CharField()
    quality_18 = models.CharField()
    quality_19 = models.CharField()
    quality_20 = models.CharField()
    quality_21 = models.CharField()
    quality_22 = models.CharField()
    quality_23 = models.CharField()
    quality_24 = models.CharField()
    quality_25 = models.CharField()
    quality_26 = models.CharField()
    quality_27 = models.CharField()
    quality_28 = models.CharField()
    quality_29 = models.CharField()
    quality_30 = models.CharField()
    quality_31 = models.CharField()
    quality_32 = models.CharField()
    quality_33 = models.CharField()
    quality_34 = models.CharField()
    quality_35 = models.CharField()
    quality_36 = models.CharField()
    quality_37 = models.CharField()
    quality_38 = models.CharField()
    quality_39 = models.CharField()
    quality_40 = models.CharField()
    quality_41 = models.CharField()
    quality_42 = models.CharField()
    quality_43 = models.CharField()
    quality_44 = models.CharField()
    quality_45 = models.CharField()
    quality_46 = models.CharField()
    quality_47 = models.CharField()
    quality_48 = models.CharField()
    quality_49 = models.CharField()
    quality_50 = models.CharField()
    quality_51 = models.CharField()
    quality_52 = models.CharField()
    quality_53 = models.CharField()
    quality_54 = models.CharField()
    quality_55 = models.CharField()
    quality_56 = models.CharField()
    quality_57 = models.CharField()
    quality_58 = models.CharField()
    quality_59 = models.CharField()
    quality_60 = models.CharField()
    quality_61 = models.CharField()
    quality_62 = models.CharField()
    quality_63 = models.CharField()
    quality_64 = models.CharField()
    quality_65 = models.CharField()
    quality_66 = models.CharField()

    birth = models.IntegerField(
        max=2017,
        min=1900,
        doc="""Please choose one of the choices""",
    )


    gender = models.CharField(
        choices=['Female', 'Male', 'Other'],
        doc="""Please choose one of the choices""",
    )

    state = models.CharField(
        choices=[
            ("AL", 'Alabama'),
            ("AK", 'Alaska'),
            ("AZ", 'Arizona'),
            ("AR", 'Arkansas'),
            ("CA", 'California'),
            ("CO", 'Colorado'),
            ("CT", 'Connecticut'),
            ("DE", 'Delaware'),
            ("DC", 'District Of Columbia'),
            ("FL", 'Florida'),
            ("GA", 'Georgia'),
            ("HI", 'Hawaii'),
            ("ID", 'Idaho'),
            ("IL", 'Illinois'),
            ("IN", 'Indiana'),
            ("IA", 'Iowa'),
            ("KS", 'Kansas'),
            ("KY", 'Kentucky'),
            ("LA", 'Louisiana'),
            ("ME", 'Maine'),
            ("MD", 'Maryland'),
            ("MA", 'Massachusetts'),
            ("MI", 'Michigan'),
            ("MN", 'Minnesota'),
            ("MS", 'Mississippi'),
            ("MO", 'Missouri'),
            ("MT", 'Montana'),
            ("NE", 'Nebraska'),
            ("NV", 'Nevada'),
            ("NH", 'New Hampshire'),
            ("NJ", 'New Jersey'),
            ("NM", 'New Mexico'),
            ("NY", 'New York'),
            ("NC", 'North Carolina'),
            ("ND", 'North Dakota'),
            ("OH", 'Ohio'),
            ("OK", 'Oklahoma'),
            ("OR", 'Oregon'),
            ("PA", 'Pennsylvania'),
            ("RI", 'Rhode Island'),
            ("SC", 'South Carolina'),
            ("SD", 'South Dakota'),
            ("TN", 'Tennessee'),
            ("TX", 'Texas'),
            ("UT", 'Utah'),
            ("VT", 'Vermont'),
            ("VA", 'Virginia'),
            ("WA", 'Washington'),
            ("WV", 'West Virginia'),
            ("WI", 'Wisconsin'),
            ("WY", 'Wyoming'),
            ("AS", 'American Samoa'),
            ("GU", 'Guam'),
            ("MP", 'Northern Mariana Islands'),
            ("PR", 'Puerto Rico'),
            ("UM", 'United States Minor Outlying Islands'),
            ("VI", 'Virgin Islands')],
        doc="""Please choose one of the choices""",
    )

    education = models.CharField(
        choices=['Female', 'Male', 'Other'],
        doc="""Please choose one of the choices""",
    )

    race = models.CharField(
        choices=['Female', 'Male', 'Other'],
        doc="""Please choose one of the choices""",
    )

    income = models.IntegerField(
        choices=[0, 1],
        doc="""Please choose one of the choices""",
    )